version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - env.example
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - api-gateway-network

  api-gateway-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_GATEWAY_URL=http://api-gateway:3000
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - api-gateway-network

  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - api-gateway-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge

volumes:
  pgdata:
  redisdata: 